# Generated by Django 4.2.28 on 2026-02-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('general', 'General Inquiry'), ('collaboration', 'Collaboration Request'), ('bug report', 'Bug Report')], default='general', max_length=50),
        ),
    ]
