# Generated by Django 4.2.28 on 2026-02-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_contact_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('bug report', 'Bug Report'), ('collaboration', 'Collaboration Request'), ('general', 'General Inquiry')], default='general', max_length=50),
        ),
    ]
