# Generated by Django 4.2.28 on 2026-02-17 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_order_cart_id_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cartitem',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderitem', to='cart.cartitem'),
        ),
    ]
