# Generated by Django 4.2.28 on 2026-02-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_orderitem_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contactno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
