# Generated by Django 4.2.28 on 2026-02-20 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_discountcode_max_uses'),
        ('cart', '0011_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(blank=True, help_text='Applied discount code to this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='products.discountcode'),
        ),
    ]
