# Generated by Django 4.2.28 on 2026-02-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='title',
            field=models.CharField(default='Great Item', max_length=255),
            preserve_default=False,
        ),
    ]
