# Generated by Django 4.2.28 on 2026-02-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productreview_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_id']},
        ),
    ]
