# Generated by Django 4.2.28 on 2026-02-19 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productsizes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductSizes',
            new_name='ProductSize',
        ),
    ]
