# Generated by Django 4.2.28 on 2026-02-20 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_productsizes_productsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Null means this discount applies to all categories', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.category')),
                ('product', models.ForeignKey(blank=True, help_text='Null means this discount applies to all products', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Null means this code applies to all categories', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='products.category')),
            ],
        ),
        migrations.AddConstraint(
            model_name='productdiscount',
            constraint=models.CheckConstraint(check=models.Q(('discount_percentage__gte', 0), ('discount_percentage__lte', 100)), name='check_product_discount_percentage'),
        ),
        migrations.AddConstraint(
            model_name='discountcode',
            constraint=models.CheckConstraint(check=models.Q(('discount_percentage__gte', 0), ('discount_percentage__lte', 100)), name='check_code_discount_percentage'),
        ),
    ]
