# Generated by Django 4.2.28 on 2026-02-20 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productdiscount_discountcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdiscount',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Null means this discount applies to all categories', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_discounts', to='products.category'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Null means this discount applies to all products', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_discounts', to='products.product'),
        ),
    ]
