# Generated by Django 4.2.28 on 2026-02-20 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_additional_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additional_images',
        ),
    ]
