# Generated by Django 4.2.28 on 2026-02-20 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdiscount',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Null means this discount applies to all categories', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='products.category'),
        ),
    ]
